// API Configuration
// Prefer injected runtime API base when present (generated by build)
const API_BASE = (() => {
  if (typeof window !== 'undefined' && window.VITE_API_BASE) return window.VITE_API_BASE;
  const hostname = window.location.hostname;
  
  // Development environments
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    return 'http://localhost:5005/api/v1';
  }
  
  // Production - Railway backend
  // IMPORTANT: In production, this MUST be set via VITE_API_BASE environment variable
  // If empty, payment and other API calls will fail
  return '';
})();

window.API_BASE = API_BASE;

// Supabase Configuration - Load from environment or use fallback
window.VITE_SUPABASE_URL = window.VITE_SUPABASE_URL || 'https://luxyimqeaclnyivmmatm.supabase.co';
window.VITE_SUPABASE_ANON_KEY = window.VITE_SUPABASE_ANON_KEY || '';

// Validate critical configuration
if (!window.VITE_SUPABASE_ANON_KEY) {
  console.warn('[config] ⚠️ WARNING: VITE_SUPABASE_ANON_KEY not configured. Auth will not work.');
}

// Masked logging for development
if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
  try {
    const maskedUrl = window.VITE_SUPABASE_URL ? window.VITE_SUPABASE_URL.replace(/(https?:\/\/)([^@]{4}).*/, '$1$2...') : 'missing';
    const anon = window.VITE_SUPABASE_ANON_KEY ? (window.VITE_SUPABASE_ANON_KEY.slice(0, 6) + '...' + window.VITE_SUPABASE_ANON_KEY.slice(-6)) : 'missing';
    console.log('[config] Development setup:', { apiBase: API_BASE, supabaseUrl: maskedUrl, anonKey: anon });
  } catch (e) {
    /* ignore */
  }
}
